export type SocialPromptCategory =
  | "Hooks"
  | "Vente"
  | "Leads"
  | "Engagement"
  | "Autorité"
  | "Objections"
  | "Storytelling"
  | "Carrousel"
  | "Reel"
  | "CTA"
  | "MRR"
  | "Personas"
  | "Conseils"
  | "Algorithmes"
  | "Viralité"
  | "Conversion"
  | "Stratégie"
  | "Conseils 90 jours";

export type SocialPromptTemplate = {
  id: string;
  category: SocialPromptCategory;
  title: string;
  description: string;
  prompt: string;
};

const RULES =
  "Règles absolues : contenu directement publiable, orienté résultat tangible, zéro blabla théorique, zéro explication méta, zéro phrase corporate, zéro formulation générique, aucune mention de marque, plateforme ou outil non demandé par l’utilisateur. Écris comme un copywriter senior spécialisé marketing digital, psychologie d’achat, contenu social, algorithmes, autorité et conversion. Le contenu doit aider l’utilisateur à conseiller son audience, paraître crédible, créer de la confiance et provoquer une action naturelle.";

export const SOCIAL_PROMPT_LIBRARY: SocialPromptTemplate[] = [
  {
    id: "hook-cost-inaction",
    category: "Hooks",
    title: "Coût invisible",
    description: "Fait sentir ce que l’inaction coûte vraiment.",
    prompt: `Crée 10 hooks qui révèlent le coût invisible du problème de l’audience. Chaque hook doit être court, spécifique, émotionnel et orienté résultat. ${RULES}`,
  },
  {
    id: "hook-truth-soft",
    category: "Hooks",
    title: "Vérité inconfortable",
    description: "Une vérité forte sans agresser.",
    prompt: `Crée 10 hooks qui commencent par une vérité inconfortable mais utile. Le lecteur doit penser : « c’est exactement ça ». ${RULES}`,
  },
  {
    id: "hook-objection-line1",
    category: "Hooks",
    title: "Objection ligne 1",
    description: "Transforme une objection en accroche.",
    prompt: `Crée 10 hooks qui ouvrent directement sur l’objection principale de l’audience, puis la retournent avec finesse. ${RULES}`,
  },
  {
    id: "hook-mirror-thought",
    category: "Hooks",
    title: "Pensée miroir",
    description: "Lit dans la tête du lecteur.",
    prompt: `Crée 10 hooks qui formulent une pensée intime que l’audience ressent mais n’ose pas dire. ${RULES}`,
  },
  {
    id: "hook-pattern-break",
    category: "Hooks",
    title: "Pattern interrupt",
    description: "Casse le scroll sans putaclic.",
    prompt: `Crée 10 hooks inattendus, crédibles et courts qui cassent le discours habituel du marché. ${RULES}`,
  },
  {
    id: "hook-before-after-gap",
    category: "Hooks",
    title: "Écart avant / après",
    description: "Montre la distance entre blocage et résultat.",
    prompt: `Crée 10 hooks basés sur l’écart entre la situation actuelle de l’audience et le résultat qu’elle veut obtenir. ${RULES}`,
  },
  {
    id: "hook-false-problem",
    category: "Hooks",
    title: "Faux problème",
    description: "Révèle la vraie cause.",
    prompt: `Crée 10 hooks qui commencent par « le problème n’est pas... » puis révèlent la vraie cause du blocage. ${RULES}`,
  },
  {
    id: "hook-silent-frustration",
    category: "Hooks",
    title: "Frustration silencieuse",
    description: "Capte une douleur rarement exprimée.",
    prompt: `Crée 10 hooks sur une frustration silencieuse de l’audience, avec un ton humain, net et premium. ${RULES}`,
  },
  {
    id: "hook-result-specific",
    category: "Hooks",
    title: "Résultat spécifique",
    description: "Promesse claire sans miracle.",
    prompt: `Crée 10 hooks centrés sur un résultat concret et désirable, sans promesse irréaliste. ${RULES}`,
  },
  {
    id: "hook-anti-generic",
    category: "Hooks",
    title: "Anti-contenu générique",
    description: "Fait sortir du contenu banal.",
    prompt: `Crée 10 hooks qui dénoncent une erreur de contenu générique et donnent envie de lire la suite. ${RULES}`,
  },
  {
    id: "advice-authority-simple",
    category: "Conseils",
    title: "Conseil d’autorité simple",
    description: "Donne un conseil que l’audience veut sauvegarder.",
    prompt: `Crée un post conseil d’expert qui donne une seule idée forte, simple et directement applicable par l’audience. ${RULES}`,
  },
  {
    id: "advice-what-to-do-today",
    category: "Conseils",
    title: "À faire aujourd’hui",
    description: "Transforme le conseil en action immédiate.",
    prompt: `Crée un post qui donne à l’audience une action simple à faire aujourd’hui pour avancer vers son objectif. ${RULES}`,
  },
  {
    id: "advice-stop-doing",
    category: "Conseils",
    title: "Arrête de faire ça",
    description: "Conseil utile sous forme d’arrêt.",
    prompt: `Crée un post conseil qui commence par ce que l’audience doit arrêter de faire, puis explique quoi faire à la place. ${RULES}`,
  },
  {
    id: "advice-beginner-mistake",
    category: "Conseils",
    title: "Erreur débutant",
    description: "Fait paraître l’utilisateur expérimenté.",
    prompt: `Crée un post qui expose une erreur fréquente de débutant dans la niche de l’utilisateur et donne une correction simple. ${RULES}`,
  },
  {
    id: "advice-saveable-framework",
    category: "Conseils",
    title: "Framework sauvegardable",
    description: "Mini méthode utile en 3 étapes.",
    prompt: `Crée un post conseil avec une méthode en 3 étapes, mémorisable, concrète et adaptée à l’audience. ${RULES}`,
  },
  {
    id: "advice-one-rule",
    category: "Conseils",
    title: "Une règle à retenir",
    description: "Autorité claire et simple.",
    prompt: `Crée un post autour d’une règle unique que l’audience devrait retenir pour obtenir un meilleur résultat. ${RULES}`,
  },
  {
    id: "advice-if-i-started-again",
    category: "Conseils",
    title: "Si je recommençais",
    description: "Conseil crédible et personnel.",
    prompt: `Crée un post « si je devais recommencer aujourd’hui » avec conseils précis, utiles et non génériques. ${RULES}`,
  },
  {
    id: "advice-common-trap",
    category: "Conseils",
    title: "Piège courant",
    description: "Aide l’audience à éviter une erreur.",
    prompt: `Crée un post qui révèle un piège courant dans la niche, explique pourquoi il bloque les résultats et donne une alternative. ${RULES}`,
  },
  {
    id: "advice-mini-audit",
    category: "Conseils",
    title: "Mini audit audience",
    description: "Permet à l’audience de s’auto-diagnostiquer.",
    prompt: `Crée un post mini-audit avec 5 signes qui montrent que l’audience doit corriger son approche. ${RULES}`,
  },
  {
    id: "advice-content-routine",
    category: "Conseils",
    title: "Routine contenu",
    description: "Aide à publier sans page blanche.",
    prompt: `Crée un post conseil qui donne une routine simple pour créer du contenu sans repartir de zéro. ${RULES}`,
  },
  {
    id: "algo-first-seconds",
    category: "Algorithmes",
    title: "Premières secondes",
    description: "Explique pourquoi le début compte.",
    prompt: `Crée un post conseil sur l’importance des premières secondes / premières lignes pour retenir l’attention. ${RULES}`,
  },
  {
    id: "algo-watch-time",
    category: "Algorithmes",
    title: "Watch time",
    description: "Rend l’algorithme compréhensible.",
    prompt: `Crée un post qui explique le watch time simplement et comment l’améliorer avec une structure de contenu claire. ${RULES}`,
  },
  {
    id: "algo-saves",
    category: "Algorithmes",
    title: "Sauvegardes",
    description: "Créer du contenu sauvegardable.",
    prompt: `Crée un post qui montre comment créer un contenu que les gens ont envie de sauvegarder. ${RULES}`,
  },
  {
    id: "algo-comments",
    category: "Algorithmes",
    title: "Commentaires qualifiés",
    description: "Favorise des réponses utiles.",
    prompt: `Crée un post conseil sur comment déclencher des commentaires qualifiés sans mendier l’engagement. ${RULES}`,
  },
  {
    id: "algo-retention-loop",
    category: "Algorithmes",
    title: "Boucle de rétention",
    description: "Maintient l’attention jusqu’à la fin.",
    prompt: `Crée un post qui explique une structure simple pour garder l’attention du début à la fin. ${RULES}`,
  },
  {
    id: "algo-posting-time",
    category: "Algorithmes",
    title: "Heures de publication",
    description: "Conseil prudent et utile.",
    prompt: `Crée un post qui explique comment tester ses meilleurs horaires de publication sans suivre aveuglément des règles génériques. ${RULES}`,
  },
  {
    id: "algo-consistency",
    category: "Algorithmes",
    title: "Régularité",
    description: "Pourquoi publier souvent aide.",
    prompt: `Crée un post sur la régularité : pourquoi elle donne plus de données, plus de clarté et plus de chances de progression. ${RULES}`,
  },
  {
    id: "algo-recycle",
    category: "Algorithmes",
    title: "Recycler intelligemment",
    description: "Transformer 1 idée en plusieurs posts.",
    prompt: `Crée un post conseil sur comment recycler une idée forte en plusieurs formats sans lasser l’audience. ${RULES}`,
  },
  {
    id: "viral-relatable",
    category: "Viralité",
    title: "Relatable fort",
    description: "Créer le « moi aussi ».",
    prompt: `Crée un post viral doux basé sur une situation que beaucoup vivent mais peu formulent clairement. ${RULES}`,
  },
  {
    id: "viral-unpopular-opinion",
    category: "Viralité",
    title: "Opinion impopulaire douce",
    description: "Prise de position crédible.",
    prompt: `Crée un post avec une opinion impopulaire mais mature dans la niche de l’utilisateur. ${RULES}`,
  },
  {
    id: "viral-myth-break",
    category: "Viralité",
    title: "Mythe cassé",
    description: "Démonte une croyance populaire.",
    prompt: `Crée un post qui casse un mythe courant et propose une vision plus utile. ${RULES}`,
  },
  {
    id: "viral-contrast",
    category: "Viralité",
    title: "Contraste fort",
    description: "Oppose deux comportements.",
    prompt: `Crée un post basé sur un contraste net entre ce que fait la majorité et ce qui produit vraiment des résultats. ${RULES}`,
  },
  {
    id: "viral-emotional-truth",
    category: "Viralité",
    title: "Vérité émotionnelle",
    description: "Touche une tension profonde.",
    prompt: `Crée un post qui exprime une vérité émotionnelle que l’audience ressent dans sa progression. ${RULES}`,
  },
  {
    id: "viral-shareable-line",
    category: "Viralité",
    title: "Phrase partageable",
    description: "Une punchline mémorable.",
    prompt: `Crée 12 phrases fortes et partageables sur le sujet de l’utilisateur, sans cliché. ${RULES}`,
  },
  {
    id: "viral-hot-take",
    category: "Viralité",
    title: "Hot take premium",
    description: "Clivant mais propre.",
    prompt: `Crée un post hot take premium : fort, assumé, mais jamais agressif ni caricatural. ${RULES}`,
  },
  {
    id: "viral-mistake-list",
    category: "Viralité",
    title: "Liste d’erreurs",
    description: "Format simple et engageant.",
    prompt: `Crée un post avec 5 erreurs fréquentes que l’audience fait sans s’en rendre compte. ${RULES}`,
  },
  {
    id: "sale-soft-premium",
    category: "Vente",
    title: "Vente douce premium",
    description: "Vend sans forcer.",
    prompt: `Crée un post de vente douce : hook émotionnel, douleur réelle, mécanisme, transformation, invitation naturelle. ${RULES}`,
  },
  {
    id: "sale-direct-human",
    category: "Vente",
    title: "Vente directe humaine",
    description: "Commercial mais propre.",
    prompt: `Crée un post de vente directe, humain et crédible, qui donne envie de demander plus d’informations. ${RULES}`,
  },
  {
    id: "sale-offer-reframe",
    category: "Vente",
    title: "Offre désirable",
    description: "Transforme une offre banale en bénéfice.",
    prompt: `Crée un post qui reformule l’offre de l’utilisateur en bénéfices concrets, soulagement et résultat tangible. ${RULES}`,
  },
  {
    id: "sale-why-now",
    category: "Vente",
    title: "Pourquoi maintenant",
    description: "Urgence saine.",
    prompt: `Crée un post qui montre pourquoi attendre coûte plus cher que passer à l’action maintenant, sans manipulation. ${RULES}`,
  },
  {
    id: "sale-mini-case",
    category: "Vente",
    title: "Mini cas client",
    description: "Preuve qualitative sans faux chiffres.",
    prompt: `Crée un post façon mini cas client crédible : situation, blocage, déclic, action, résultat ressenti. N’invente aucun chiffre. ${RULES}`,
  },
  {
    id: "sale-cost-of-diy",
    category: "Vente",
    title: "Coût du bricolage",
    description: "Montre la limite du système D.",
    prompt: `Crée un post qui montre le coût caché des solutions bricolées et pourquoi une approche structurée change tout. ${RULES}`,
  },
  {
    id: "sale-emotional-benefit",
    category: "Vente",
    title: "Bénéfice émotionnel",
    description: "Vend le soulagement.",
    prompt: `Crée un post qui vend le bénéfice émotionnel de l’offre : clarté, sérénité, confiance, simplicité, progression. ${RULES}`,
  },
  {
    id: "sale-no-pressure",
    category: "Vente",
    title: "Sans pression",
    description: "Invitation élégante.",
    prompt: `Crée un post qui propose l’offre avec une invitation élégante, sans urgence artificielle ni pression. ${RULES}`,
  },
  {
    id: "lead-magnet-desire",
    category: "Leads",
    title: "Lead magnet désirable",
    description: "Donne envie de demander la ressource.",
    prompt: `Crée un post qui rend une ressource gratuite irrésistible en montrant le gain concret et le soulagement obtenu. ${RULES}`,
  },
  {
    id: "lead-dm-keyword",
    category: "Leads",
    title: "DM mot-clé",
    description: "Déclenche des messages privés.",
    prompt: `Crée un post court qui pousse naturellement à envoyer un mot-clé en DM pour recevoir une ressource utile. ${RULES}`,
  },
  {
    id: "lead-comment-keyword",
    category: "Leads",
    title: "Commentaire mot-clé",
    description: "Récolte des commentaires qualifiés.",
    prompt: `Crée un post qui donne envie de commenter un mot-clé tout en filtrant une audience qualifiée. ${RULES}`,
  },
  {
    id: "lead-checklist",
    category: "Leads",
    title: "Checklist utile",
    description: "Ressource simple à télécharger.",
    prompt: `Crée un post qui vend une checklist concrète qui évite une erreur, un oubli ou une perte de temps. ${RULES}`,
  },
  {
    id: "lead-audit",
    category: "Leads",
    title: "Mini audit offert",
    description: "Attire prospects chauds.",
    prompt: `Crée un post qui propose un mini audit ou diagnostic simple, avec un CTA naturel. ${RULES}`,
  },
  {
    id: "lead-quiz",
    category: "Leads",
    title: "Question diagnostic",
    description: "Fait s’auto-identifier l’audience.",
    prompt: `Crée un post avec une question diagnostic qui aide l’audience à comprendre son niveau ou son blocage. ${RULES}`,
  },
  {
    id: "eng-confession",
    category: "Engagement",
    title: "Confession relatable",
    description: "Déclenche le « moi aussi ».",
    prompt: `Crée un post confessionnel court, très humain, qui donne envie à l’audience de répondre. ${RULES}`,
  },
  {
    id: "eng-deep-question",
    category: "Engagement",
    title: "Question profonde",
    description: "Ouvre une vraie conversation.",
    prompt: `Crée 7 questions de post qui poussent l’audience à commenter son vrai blocage. ${RULES}`,
  },
  {
    id: "eng-this-or-that",
    category: "Engagement",
    title: "Choix A/B",
    description: "Simple et conversationnel.",
    prompt: `Crée un post type choix A/B qui force une prise de position simple. ${RULES}`,
  },
  {
    id: "eng-fill-blank",
    category: "Engagement",
    title: "Phrase à compléter",
    description: "Facile à commenter.",
    prompt: `Crée un post avec une phrase à compléter, liée au blocage ou au désir de l’audience. ${RULES}`,
  },
  {
    id: "eng-poll-caption",
    category: "Engagement",
    title: "Sondage caption",
    description: "Engagement léger.",
    prompt: `Crée un post qui fonctionne comme un mini sondage avec 3 options claires. ${RULES}`,
  },
  {
    id: "auth-framework",
    category: "Autorité",
    title: "Framework 3 étapes",
    description: "Crédibilité immédiate.",
    prompt: `Crée un post d’autorité avec un framework en 3 étapes, simple et mémorisable. ${RULES}`,
  },
  {
    id: "auth-myth",
    category: "Autorité",
    title: "Mythe cassé",
    description: "Positionnement expert.",
    prompt: `Crée un post qui casse un mythe du marché et propose une vision plus mature. ${RULES}`,
  },
  {
    id: "auth-diagnostic",
    category: "Autorité",
    title: "Diagnostic expert",
    description: "Montre une compréhension profonde.",
    prompt: `Crée un post diagnostic : symptômes visibles, vraie cause, erreur fréquente, meilleure approche. ${RULES}`,
  },
  {
    id: "auth-principle",
    category: "Autorité",
    title: "Principe fondateur",
    description: "Fait paraître solide.",
    prompt: `Crée un post qui présente un principe fort à appliquer dans la niche de l’utilisateur. ${RULES}`,
  },
  {
    id: "auth-teardown",
    category: "Autorité",
    title: "Analyse d’erreur",
    description: "Explique pourquoi ça bloque.",
    prompt: `Crée un post d’analyse qui démonte une erreur courante et montre la correction. ${RULES}`,
  },
  {
    id: "obj-price",
    category: "Objections",
    title: "Prix",
    description: "Retourne « trop cher ».",
    prompt: `Crée un post qui répond à l’objection prix en montrant le coût de l’inaction et la valeur du résultat. ${RULES}`,
  },
  {
    id: "obj-time",
    category: "Objections",
    title: "Temps",
    description: "Pour audience débordée.",
    prompt: `Crée un post qui répond à « je n’ai pas le temps » en montrant le rôle d’un système simple. ${RULES}`,
  },
  {
    id: "obj-legitimacy",
    category: "Objections",
    title: "Légitimité",
    description: "Aide à oser publier ou vendre.",
    prompt: `Crée un post qui aide l’audience à dépasser la peur de ne pas être légitime. ${RULES}`,
  },
  {
    id: "obj-tried",
    category: "Objections",
    title: "Déjà essayé",
    description: "Relance les sceptiques.",
    prompt: `Crée un post qui répond à « j’ai déjà essayé » avec nuance et crédibilité. ${RULES}`,
  },
  {
    id: "obj-tools",
    category: "Objections",
    title: "Trop d’outils",
    description: "Surcharge digitale.",
    prompt: `Crée un post qui répond à la saturation des outils, méthodes et contenus contradictoires. ${RULES}`,
  },
  {
    id: "story-before-after",
    category: "Storytelling",
    title: "Avant / après humain",
    description: "Mini transformation crédible.",
    prompt: `Crée un storytelling avant/après : confusion, frustration, déclic, nouvelle action, résultat ressenti. ${RULES}`,
  },
  {
    id: "story-mistake",
    category: "Storytelling",
    title: "Erreur → leçon",
    description: "Transforme l’erreur en contenu.",
    prompt: `Crée un post storytelling basé sur une erreur fréquente puis une leçon concrète. ${RULES}`,
  },
  {
    id: "story-day-life",
    category: "Storytelling",
    title: "Scène du quotidien",
    description: "Très visuel et humain.",
    prompt: `Crée un post scène du quotidien où le lecteur visualise sa propre situation. ${RULES}`,
  },
  {
    id: "story-client-avatar",
    category: "Storytelling",
    title: "Avatar client",
    description: "Histoire d’un profil type.",
    prompt: `Crée une mini-histoire autour d’un avatar client fictif mais réaliste, sans inventer de témoignage. ${RULES}`,
  },
  {
    id: "story-turning-point",
    category: "Storytelling",
    title: "Moment déclic",
    description: "Le moment où tout change.",
    prompt: `Crée un post storytelling autour d’un déclic simple qui change la façon d’agir. ${RULES}`,
  },
  {
    id: "car-conversion6",
    category: "Carrousel",
    title: "Conversion 6 slides",
    description: "Capter, convaincre, convertir.",
    prompt: `Crée un carrousel de 6 slides : hook, problème, erreur, mécanisme, mini-plan, CTA. ${RULES}`,
  },
  {
    id: "car-myth-method",
    category: "Carrousel",
    title: "Mythe → méthode",
    description: "Éducatif et sauvegardable.",
    prompt: `Crée un carrousel qui part d’un mythe courant, le démonte et propose une méthode simple. ${RULES}`,
  },
  {
    id: "car-checklist",
    category: "Carrousel",
    title: "Checklist action",
    description: "Fait sauvegarder.",
    prompt: `Crée un carrousel checklist ultra concret avec une action claire par slide. ${RULES}`,
  },
  {
    id: "car-before-after",
    category: "Carrousel",
    title: "Avant / après",
    description: "Transformation claire.",
    prompt: `Crée un carrousel qui montre l’avant, le blocage, le déclic, l’après et l’action suivante. ${RULES}`,
  },
  {
    id: "car-mistakes",
    category: "Carrousel",
    title: "5 erreurs",
    description: "Format pédagogique efficace.",
    prompt: `Crée un carrousel sur 5 erreurs fréquentes et leurs corrections simples. ${RULES}`,
  },
  {
    id: "reel-pain-fast",
    category: "Reel",
    title: "Douleur rapide",
    description: "Impact en 25 secondes.",
    prompt: `Crée un script Reel de 25 secondes : hook 2 sec, scène relatable, tension, déclic, CTA court. ${RULES}`,
  },
  {
    id: "reel-objection",
    category: "Reel",
    title: "Objection vidéo",
    description: "Répond en format court.",
    prompt: `Crée un script Reel qui répond à une objection : phrase choc, objection, retournement, exemple, CTA. ${RULES}`,
  },
  {
    id: "reel-story",
    category: "Reel",
    title: "Mini-story Reel",
    description: "Histoire courte qui vend sans vendre.",
    prompt: `Crée un script Reel storytelling : situation précise, frustration, déclic, action, invitation naturelle. ${RULES}`,
  },
  {
    id: "reel-tutorial",
    category: "Reel",
    title: "Micro tuto",
    description: "Conseil rapide filmable.",
    prompt: `Crée un script Reel micro-tuto avec 3 étapes très simples à afficher à l’écran. ${RULES}`,
  },
  {
    id: "cta-dm",
    category: "CTA",
    title: "CTA DM premium",
    description: "Fait écrire sans malaise.",
    prompt: `Crée 12 CTA premium pour inviter à envoyer un DM : doux, direct, expert, émotionnel, curiosité. ${RULES}`,
  },
  {
    id: "cta-comment",
    category: "CTA",
    title: "CTA commentaire",
    description: "Mot-clé naturel.",
    prompt: `Crée 12 CTA pour inviter à commenter un mot-clé, courts et orientés bénéfice. ${RULES}`,
  },
  {
    id: "cta-save-share",
    category: "CTA",
    title: "CTA sauvegarde / partage",
    description: "Engagement utile.",
    prompt: `Crée 12 CTA qui donnent envie de sauvegarder ou partager sans mendier l’engagement. ${RULES}`,
  },
  {
    id: "cta-click",
    category: "CTA",
    title: "CTA clic",
    description: "Pour lien / bio / page.",
    prompt: `Crée 12 CTA pour pousser à cliquer vers une ressource, page ou offre, sans agressivité. ${RULES}`,
  },
  {
    id: "mrr-stuck",
    category: "MRR",
    title: "Bloqué après achat",
    description: "Audience qui achète mais n’exécute pas.",
    prompt: `Crée un post pour une personne qui a acheté des formations ou produits digitaux mais reste bloquée au moment de publier et vendre. ${RULES}`,
  },
  {
    id: "mrr-fatigue",
    category: "MRR",
    title: "Fatigue contenu",
    description: "Le business devient un deuxième job.",
    prompt: `Crée un post sur la fatigue de devoir créer du contenu tous les jours pour vendre des produits digitaux. ${RULES}`,
  },
  {
    id: "mrr-one-shot",
    category: "MRR",
    title: "Ventes one-shot",
    description: "Sortir de la vente ponctuelle.",
    prompt: `Crée un post sur la frustration des ventes ponctuelles : vendre parfois, disparaître, recommencer à zéro. ${RULES}`,
  },
  {
    id: "mrr-trust",
    category: "MRR",
    title: "Manque de confiance",
    description: "Construire crédibilité et conversion.",
    prompt: `Crée un post expliquant pourquoi l’audience n’achète pas encore : clarté, confiance, preuve, répétition utile. ${RULES}`,
  },
  {
    id: "mrr-content-system",
    category: "MRR",
    title: "Système contenu",
    description: "Publier sans repartir de zéro.",
    prompt: `Crée un post qui montre pourquoi un système de contenu vaut mieux qu’une nouvelle formation. ${RULES}`,
  },
  {
    id: "persona-parent",
    category: "Personas",
    title: "Parent débordé",
    description: "Temps limité, besoin de simplicité.",
    prompt: `Crée un post pour une personne qui développe une activité digitale avec famille, charge mentale et peu de temps. ${RULES}`,
  },
  {
    id: "persona-salarie",
    category: "Personas",
    title: "Salarié + side business",
    description: "Avancer après le travail.",
    prompt: `Crée un post pour un salarié qui construit une activité en ligne après le travail mais se sent dispersé. ${RULES}`,
  },
  {
    id: "persona-coach",
    category: "Personas",
    title: "Coach / consultant",
    description: "Vendre son expertise sans lourdeur.",
    prompt: `Crée un post pour un coach ou consultant qui veut vendre son accompagnement sans paraître insistant. ${RULES}`,
  },
  {
    id: "persona-low-eng",
    category: "Personas",
    title: "Créateur peu engagé",
    description: "Publie mais n’obtient pas de retours.",
    prompt: `Crée un post pour quelqu’un qui publie régulièrement mais obtient peu de commentaires, leads et ventes. ${RULES}`,
  },
  {
    id: "conv-cold-warm",
    category: "Conversion",
    title: "Audience froide → tiède",
    description: "Créer la confiance.",
    prompt: `Crée un post qui transforme une audience froide en audience intéressée grâce à une tension claire et une micro-solution. ${RULES}`,
  },
  {
    id: "conv-trust",
    category: "Conversion",
    title: "Confiance avant vente",
    description: "Faire acheter plus tard.",
    prompt: `Crée un post qui construit la confiance avant de vendre, avec preuve qualitative et clarté. ${RULES}`,
  },
  {
    id: "conv-next-step",
    category: "Conversion",
    title: "Prochaine étape",
    description: "Évite le contenu sans action.",
    prompt: `Crée un post qui donne une prochaine étape logique et simple après la prise de conscience. ${RULES}`,
  },
  {
    id: "conv-offer-fit",
    category: "Conversion",
    title: "Pourquoi cette offre",
    description: "Faire comprendre l’adéquation.",
    prompt: `Crée un post qui explique pourquoi l’offre correspond à la situation de l’audience sans argumentaire lourd. ${RULES}`,
  },

  {
    id: "strategy-week-content-system",
    category: "Stratégie",
    title: "Système éditorial 7 jours",
    description: "Plan simple pour publier sans repartir de zéro.",
    prompt: `Crée une stratégie de contenu sur 7 jours pour l’audience de l’utilisateur : objectif de chaque jour, angle, format recommandé, hook, conseil à transmettre et CTA. Le plan doit préparer une génération LIVE IA complète ensuite. ${RULES}`,
  },
  {
    id: "strategy-authority-engine",
    category: "Stratégie",
    title: "Moteur d’autorité",
    description: "Alterner expertise, preuve, pédagogie et conversion.",
    prompt: `Crée une stratégie éditoriale d’autorité pour 30 jours : catégories de contenu, fréquence, objectifs, types de conseils à donner et angles de conversion douce. ${RULES}`,
  },
  {
    id: "advice-90-days-live-plan",
    category: "Conseils 90 jours",
    title: "Conseils 90 jours — LIVE IA",
    description: "Prépare un calendrier long terme de conseils experts pour l’audience.",
    prompt: `Prépare un calendrier stratégique de 90 jours de conseils experts pour l’audience de l’utilisateur. Pour chaque jour : thème, angle, objectif, format recommandé, conseil à donner, idée de hook, CTA naturel, astuce algorithme. Ne génère pas un contenu générique : chaque jour doit apporter une vraie valeur différente. ${RULES}`,
  },
  {
    id: "advice-90-days-authority",
    category: "Conseils 90 jours",
    title: "90 jours autorité",
    description: "Devenir la personne intéressante à suivre dans sa niche.",
    prompt: `Crée un plan de 90 jours pour positionner l’utilisateur comme une référence utile dans sa niche : conseils, erreurs à éviter, mini-frameworks, objections, cas pratiques, contenus sauvegardables, posts conversationnels et appels à l’action. ${RULES}`,
  },
];

export const SOCIAL_PROMPT_CATEGORIES: SocialPromptCategory[] = [
  "Hooks",
  "Vente",
  "Leads",
  "Engagement",
  "Autorité",
  "Objections",
  "Storytelling",
  "Carrousel",
  "Reel",
  "CTA",
  "MRR",
  "Personas",
  "Conseils",
  "Algorithmes",
  "Viralité",
  "Conversion",
  "Stratégie",
  "Conseils 90 jours",
];
